# Generated by Django 4.2.6 on 2023-10-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('description', models.TextField(verbose_name='description')),
                ('isbn', models.CharField(max_length=150, verbose_name='isbn')),
                ('genres', models.TextField(verbose_name='genres')),
                ('likedpercentage', models.IntegerField(verbose_name='likedPercent')),
                ('coverImg', models.URLField(verbose_name='coverImg')),
            ],
        ),
    ]
