# Generated by Django 4.2.6 on 2023-10-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImg',
            field=models.TextField(verbose_name='coverImg'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(max_length=255, verbose_name='title'),
        ),
    ]
