# Generated by Django 4.2.6 on 2023-11-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userprofile_remove_book_likedpercentage_book_awards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.TextField(),
        ),
    ]
